const WELCOME_TO_MINI_TEST = 'COOPMART MINI TEST ONLINE';
const SIGN_UP = 'ĐĂNG KÝ';
const LOGIN = 'ĐĂNG NHẬP';
const LOGOUT = 'THOÁT';

const PLEASE_ENTER_YOUR_FULL_NAME = 'VUI LÒNG ĐIỀN HỌ VÀ TÊN';
const FULL_NAME_PLACE_HOLDER = 'NGUYỄN VĂN A';
const USER_NAME_CAN_NOT_BE_EMPTY = 'HỌ VÀ TÊN KHÔNG ĐƯỢC ĐỂ TRỐNG';
const PLEASE_SELECT_YOUR_DEPARTMENT = 'VUI LÒNG LỰA CHỌN BỘ PHẬN BẠN LÀM VIỆC';
const DEPARTMENT_CAN_NOT_BE_EMPTY = 'BỘ PHẬN BẠN LÀM VIỆC KHÔNG ĐƯỢC ĐỂ TRỐNG';

const INVALID_CREDENTIALS = 'ĐĂNG NHẬP KHÔNG THÀNH CÔNG';
const CONGRATULATIONS = 'XIN CHÚC MỪNG';
const DONE_TEST_EXAM = 'BẠN ĐÃ HOÀN THÀNH BÀI TEST';

const BEFORE_TIME_UP = 'THỜI GIAN LÀM BÀI CÒN 2 PHÚT';
const TIME_UP = 'HẾT GIỜ LÀM BÀI';
const SUBMIT_TEST = 'NỘP BÀI';

const QUESTION = 'CÂU HỎI';
const PLEASE_TRY_AGAIN = 'VUI LÒNG THỬ LẠI';

export {
    WELCOME_TO_MINI_TEST,
    SIGN_UP,
    LOGIN,
    LOGOUT,
    PLEASE_ENTER_YOUR_FULL_NAME,
    FULL_NAME_PLACE_HOLDER,
    USER_NAME_CAN_NOT_BE_EMPTY,
    INVALID_CREDENTIALS,
    CONGRATULATIONS,
    DONE_TEST_EXAM,
    BEFORE_TIME_UP,
    TIME_UP,
    SUBMIT_TEST,
    QUESTION,
    PLEASE_TRY_AGAIN,
    PLEASE_SELECT_YOUR_DEPARTMENT,
    DEPARTMENT_CAN_NOT_BE_EMPTY
}